name: Android-sovelluksen rakennus
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Asenna JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
          
      - name: Anna luvat
        run: chmod +x ./gradlew
        
      - name: Rakenna projekti
        run: ./gradlew assemble
